export const DOOR_COLOR_LIST = [
  { id: 16, name: "MDF,, 18T, 필름 부착용 합판 (색깔 상관X)", image: "/img/color-new-list/film-attached-plywood.png" },
  { id: 1, name: "MDF, 한솔, 18T, 크림화이트", image: "/img/color-new-list/hansol-cream-white.png" },
  { id: 2, name: "MDF, 한솔, 18T, 퍼펙트화이트", image: "/img/color-new-list/hansol-perfect-white.png" },
  { id: 3, name: "MDF, 한솔, 18T, 새틴베이지", image: "/img/color-new-list/hansol-satin-beige.png" },
  { id: 4, name: "MDF, 한솔, 18T, 코튼블루", image: "/img/color-new-list/hansol-cotton-blue.png" },
  { id: 5, name: "MDF, 한솔, 18T, 도브화이트", image: "/img/color-new-list/hansol-dove-white.png" },
  { id: 6, name: "MDF, 한솔, 18T, 포그그레이", image: "/img/color-new-list/hansol-fog-gray.png" },
  { id: 7, name: "MDF, 한솔, 18T, 샌드그레이", image: "/img/color-new-list/hansol-sand-gray.png" },
  { id: 8, name: "MDF, 한솔, 18T, 테네시월넛", image: "/img/color-new-list/hansol-tennessee-walnut.png" },
  { id: 9, name: "MDF, 한솔, 18T, 베이내츄럴오크", image: "/img/color-new-list/hansol-bay-natural-oak.png" },
  { id: 10, name: "MDF, 한솔, 18T, 내츄럴크랙오크", image: "/img/color-new-list/hansol-natural-crack-oak.png" },
  { id: 11, name: "MDF, 한솔, 18T, 칼프브라운", image: "/img/color-new-list/hansol-calf-brown.png" },
  { id: 12, name: "MDF, 한솔, 18T, 콘크리트샌드", image: "/img/color-new-list/hansol-concrete-sand.png" },
  { id: 13, name: "MDF, 한솔, 18T, 콘크리트화이트", image: "/img/color-new-list/hansol-concrete-white.png" },
  { id: 14, name: "MDF, 동화, 18T, 밀크화이트", image: "/img/color-new-list/dongwha-milk-white.png" },
  { id: 15, name: "MDF, 동화, 18T, 카본그레이", image: "/img/color-new-list/dongwha-carbon-gray.png" },
] as const;
export const CABINET_COLOR_LIST = [
  { id: 16, name: "MDF,, 18T, 필름 부착용 합판 (색깔 상관X)", image: "/img/color-new-list/film-attached-plywood.png" },
  { id: 1, name: "MDF, 한솔, 18T, 크림화이트", image: "/img/color-new-list/hansol-cream-white.png" },
  { id: 2, name: "MDF, 한솔, 18T, 퍼펙트화이트", image: "/img/color-new-list/hansol-perfect-white.png" },
  { id: 3, name: "MDF, 한솔, 18T, 새틴베이지", image: "/img/color-new-list/hansol-satin-beige.png" },
  { id: 4, name: "MDF, 한솔, 18T, 코튼블루", image: "/img/color-new-list/hansol-cotton-blue.png" },
  { id: 5, name: "MDF, 한솔, 18T, 도브화이트", image: "/img/color-new-list/hansol-dove-white.png" },
  { id: 6, name: "MDF, 한솔, 18T, 포그그레이", image: "/img/color-new-list/hansol-fog-gray.png" },
  { id: 7, name: "MDF, 한솔, 18T, 샌드그레이", image: "/img/color-new-list/hansol-sand-gray.png" },
  { id: 8, name: "MDF, 한솔, 18T, 테네시월넛", image: "/img/color-new-list/hansol-tennessee-walnut.png" },
  { id: 9, name: "MDF, 한솔, 18T, 베이내츄럴오크", image: "/img/color-new-list/hansol-bay-natural-oak.png" },
  { id: 10, name: "MDF, 한솔, 18T, 내츄럴크랙오크", image: "/img/color-new-list/hansol-natural-crack-oak.png" },
  { id: 11, name: "MDF, 한솔, 18T, 칼프브라운", image: "/img/color-new-list/hansol-calf-brown.png" },
  { id: 12, name: "MDF, 한솔, 18T, 콘크리트샌드", image: "/img/color-new-list/hansol-concrete-sand.png" },
  { id: 13, name: "MDF, 한솔, 18T, 콘크리트화이트", image: "/img/color-new-list/hansol-concrete-white.png" },
  { id: 14, name: "MDF, 동화, 18T, 밀크화이트", image: "/img/color-new-list/dongwha-milk-white.png" },
  { id: 15, name: "MDF, 동화, 18T, 카본그레이", image: "/img/color-new-list/dongwha-carbon-gray.png" },
] as const;
export const FINISH_COLOR_LIST = [
  { id: 20, name: "MDF,, 18T, 필름 부착용 합판 (색깔 상관X)", image: "/img/color-new-list/film-attached-plywood.png" },
  { id: 1, name: "MDF, 한솔, 18T, 크림화이트", image: "/img/color-new-list/hansol-cream-white.png" },
  { id: 2, name: "MDF, 한솔, 18T, 퍼펙트화이트", image: "/img/color-new-list/hansol-perfect-white.png" },
  { id: 3, name: "MDF, 한솔, 18T, 새틴베이지", image: "/img/color-new-list/hansol-satin-beige.png" },
  { id: 4, name: "MDF, 한솔, 18T, 코튼블루", image: "/img/color-new-list/hansol-cotton-blue.png" },
  { id: 5, name: "MDF, 한솔, 18T, 도브화이트", image: "/img/color-new-list/hansol-dove-white.png" },
  { id: 6, name: "MDF, 한솔, 18T, 포그그레이", image: "/img/color-new-list/hansol-fog-gray.png" },
  { id: 7, name: "MDF, 한솔, 18T, 샌드그레이", image: "/img/color-new-list/hansol-sand-gray.png" },
  { id: 8, name: "MDF, 한솔, 18T, 테네시월넛", image: "/img/color-new-list/hansol-tennessee-walnut.png" },
  { id: 9, name: "MDF, 한솔, 18T, 베이내츄럴오크", image: "/img/color-new-list/hansol-bay-natural-oak.png" },
  { id: 10, name: "MDF, 한솔, 18T, 내츄럴크랙오크", image: "/img/color-new-list/hansol-natural-crack-oak.png" },
  { id: 11, name: "MDF, 한솔, 18T, 칼프브라운", image: "/img/color-new-list/hansol-calf-brown.png" },
  { id: 12, name: "MDF, 한솔, 18T, 콘크리트샌드", image: "/img/color-new-list/hansol-concrete-sand.png" },
  { id: 13, name: "MDF, 한솔, 18T, 콘크리트화이트", image: "/img/color-new-list/hansol-concrete-white.png" },
  { id: 14, name: "MDF, 동화, 18T, 밀크화이트", image: "/img/color-new-list/dongwha-milk-white.png" },
  { id: 15, name: "MDF, 동화, 18T, 카본그레이", image: "/img/color-new-list/dongwha-carbon-gray.png" },
  { id: 20, name: "PB, 한솔, 18T, 파타고니아크림", image: "/img/color-new-list/hansol-patagonia-cream.png" },
  { id: 16, name: "PB,, 18T, 헤링본", image: "/img/color-new-list/herringbone.png" },
  { id: 17, name: "PB,, 15T, 헤링본", image: "/img/color-new-list/herringbone.png" },
  { id: 18, name: "PB, 동화, 3T 우라, 헤링본", image: "/img/color-new-list/herringbone.png" },
  { id: 19, name: "PB,, 15T, 헤링본 - 미백색", image: "/img/color-new-list/herringbone-off-white.png" },
] as const;


// export const BODY_MATERIAL_LIST = ["헤링본 PB 15T", "헤링본 PB 18T", "한솔 파타고니아크림 LPM 18T"];
