export const COLOR_LIST = [
  { name: "MDF, 한솔, 18T, 크림화이트", image: "/img/Checker.png" },
  { name: "MDF, 한솔, 18T, 퍼펙트화이트", image: "/img/Checker.png" },
  { name: "MDF, 한솔, 18T, 도브화이트", image: "/img/Checker.png" },
  { name: "MDF, 한솔, 18T, 포그그레이", image: "/img/Checker.png" },
  { name: "MDF, 한솔, 18T, 샌드그레이", image: "/img/Checker.png" },
  { name: "MDF, 한솔, 18T, 테네시월넛", image: "/img/Checker.png" },
  { name: "MDF, 한솔, 18T, 베이내츄럴오크", image: "/img/Checker.png" },
  { name: "MDF, 한솔, 18T, 내츄럴크랙오크", image: "/img/Checker.png" },
  { name: "MDF, 한솔, 18T, 칼프브라운우드", image: "/img/Checker.png" },
  { name: "MDF, 한솔, 18T, 콘크리트샌드", image: "/img/Checker.png" },
  { name: "MDF, 한솔, 18T, 콘크리트화이트", image: "/img/Checker.png" },
  { name: "MDF, 한솔, 18T, 새틴베이지", image: "/img/Checker.png" },
  { name: "MDF, 한솔, 18T, 코튼블루", image: "/img/Checker.png" },
  { name: "MDF, 기타, 18T, 연아이보리 무광", image: "/img/Checker.png" },
  { name: "MDF, 동화, 18T, 밀크화이트", image: "/img/Checker.png" },
  { name: "MDF, 동화, 18T, 카본그레이", image: "/img/Checker.png" },
  { name: "PB, 동화, 15T, 헤링본", image: "/img/Checker.png" },
  { name: "PB, 동화, 15T, 헤링본-미백색", image: "/img/Checker.png" },
  { name: "PB, 동화, 18T, 헤링본", image: "/img/Checker.png" },
  { name: "PB, 동화, 3T 우라, 헤링본", image: "/img/Checker.png" },
  { name: "PB, 한솔, 18T, 파타고니아 크림", image: "/img/Checker.png" },
] as const;
